### ISSUE TITLE
only size-1 arrays can be converted to Python scalars

### ISSUE THREAD

**Issue by sivaji123256** [deshwalmahesh/yolov7-deepsort-tracking#1]
@deshwalmahesh I have replicated your on couple of videos.On one of the video, it was raising the above error.Also,Can you please look into the TensorRT version of the same? I am happy to contribute to the TensorRT model creation.

**Comment by deshwalmahesh** [comment]
Hey @sivaji123256  Thanks for checking it out. Can you paste the `traceback` here? It's a generic error from `numpy`. Even though I got no experience with `TensorRT`  but I'll be glad to work on that as soon as I'm done with a new paper on segmentation after 20th.

**Comment by jgomeher83** [comment]
hi I have the same error 
only size-1 arrays can be converted to Python scalars #1

**Comment by deshwalmahesh** [comment]
> hi I have the same error only size-1 arrays can be converted to Python scalars #1

Hey @jgomeher83  can you just paste the `traceback` or entire error or maybe which line is causing it. I might not have handled the case where there are no detections by the `YOLOv7` model.

**Comment by prsnkmr** [comment]
hi i have the same error 
only size-1 arrays can be converted to Python Scalars

Traceback (most recent call last):
  File "/home/Downloads/new/yolov7-deepsort-tracking/yolov7deepsort.py", line 8, in <module>
    tracker.track_video('yolov7-deepsort-tracking/video1.mp4', output="yolov7-deepsort-tracking/IO_data/output/yolov7_tracking.avi", show_live = False, skip_frames = 0, count_objects = True, verbose=1)
  File "/home/Downloads/new/yolov7-deepsort-tracking/bridge_wrapper.py", line 112, in track_video
    class_indx = int(classes[i])
TypeError: only size-1 arrays can be converted to Python scalars

will you please look into it and resove it.
Thanks in advance.

**Comment by DARK-art108** [comment]
Same error here, while performing custom video inference.

**Comment by prsnkmr** [comment]
Whenever there is no detections in the frame, 
detector.detect function passes the actual image as output thats the reason we are facing the error.

Change the lines 105,109 in detection_helpers.py  to avoid the errror as shown in the image

![error resolver](https://user-images.githubusercontent.com/110216641/181717939-f0998b99-690b-4664-b850-e5e47b839567.png)

and also change lines in bridge_wrappers.py as shown in below image.

if yolo_dets is not None:
                    if frame_num==65:
                        print(yolo_dets)
                    if frame_num==66:
                        filename='frame_66.jpg'
                        cv2.imwrite(filename,frame)
                    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                    
                    bboxes = yolo_dets[:,:4]
                    bboxes[:,2] = bboxes[:,2] - bboxes[:,0] # convert from xyxy to xywh
                    bboxes[:,3] = bboxes[:,3] - bboxes[:,1]

                    scores = yolo_dets[:,4]
                    classes = yolo_dets[:,-1]
                    
                    num_objects = bboxes.shape[0]
                            # ---------------------------------------- DETECTION PART COMPLETED ---------------------------------------------------------------------
                            
                    names = []
                    
                    for i in range(num_objects): # loop through objects and use class index to get class name
                            class_indx = int(classes[i])
                            class_name = self.class_names[class_indx]
                            names.append(class_name)


                    names = np.array(names)
                    count = len(names)

                    if count_objects:
                        cv2.putText(frame, "Objects being tracked: {}".format(count), (5, 35),cv2.FONT_HERSHEY_COMPLEX_SMALL,1.5, (0, 0, 0), 2)

                    # ---------------------------------- DeepSORT tacker work starts here ------------------------------------------------------------
                    features = self.encoder(frame, bboxes) # encode detections and feed to tracker. [No of BB / detections per frame, embed_size]
                    detections = [Detection(bbox, score, class_name, feature) for bbox, score, class_name, feature in zip(bboxes, scores, names, features)] # [No of BB per frame] deep_sort.detection.Detection object

                    cmap = plt.get_cmap('tab20b') #initialize color map
                    colors = [cmap(i)[:3] for i in np.linspace(0, 1, 20)]

                    boxs = np.array([d.tlwh for d in detections])  # run non-maxima supression below
                    scores = np.array([d.confidence for d in detections])
                    classes = np.array([d.class_name for d in detections])
                    indices = preprocessing.non_max_suppression(boxs, classes, self.nms_max_overlap, scores)
                    detections = [detections[i] for i in indices]       

                    self.tracker.predict()  # Call the tracker
                    self.tracker.update(detections) #  updtate using Kalman Gain

                    for track in self.tracker.tracks:  # update new findings AKA tracks
                        if not track.is_confirmed() or track.time_since_update > 1:
                            continue 
                        bbox = track.to_tlbr()
                        class_name = track.get_class()
                
                        color = colors[int(track.track_id) % len(colors)]  # draw bbox on screen
                        color = [i * 255 for i in color]
                        cv2.rectangle(frame, (int(bbox[0]), int(bbox[1])), (int(bbox[2]), int(bbox[3])), color, 2)
                        cv2.rectangle(frame, (int(bbox[0]), int(bbox[1]-30)), (int(bbox[0])+(len(class_name)+len(str(track.track_id)))*17, int(bbox[1])), color, -1)
                        cv2.putText(frame, class_name + " : " + str(track.track_id),(int(bbox[0]), int(bbox[1]-11)),0, 0.6, (255,255,255),1, lineType=cv2.LINE_AA)    

                        if verbose == 2:
                            print("Tracker ID: {}, Class: {},  BBox Coords (xmin, ymin, xmax, ymax): {}".format(str(track.track_id), class_name, (int(bbox[0]), int(bbox[1]), int(bbox[2]), int(bbox[3]))))

**Comment by prsnkmr** [comment]
when there is not detections in the frame,it will pass the input frame as output of the detections.detect function.

To  avoid the error change the lines 105,109 in detection_helpers.py as shown in the image.
![error resolver](https://user-images.githubusercontent.com/110216641/181720949-b3ac877d-ade1-4943-b782-663633848cf8.png)

And also indent the lines from 100 to 142 in bridge_werapper.py as shown in the code

if yolo_dets is not None:
                    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                    bboxes = yolo_dets[:,:4]
                    bboxes[:,2] = bboxes[:,2] - bboxes[:,0] # convert from xyxy to xywh
                    bboxes[:,3] = bboxes[:,3] - bboxes[:,1]
                    scores = yolo_dets[:,4]
                    classes = yolo_dets[:,-1]
                    num_objects = bboxes.shape[0]
                            # ---------------------------------------- DETECTION PART COMPLETED ---------------------------------------------------------------------      
                    names = []
                    for i in range(num_objects): # loop through objects and use class index to get class name
                            class_indx = int(classes[i])
                            class_name = self.class_names[class_indx]
                            names.append(class_name)
                    names = np.array(names)
                    count = len(names)
                    if count_objects:
                        cv2.putText(frame, "Objects being tracked: {}".format(count), (5, 35), cv2.FONT_HERSHEY_COMPLEX_SMALL, 1.5, (0, 0, 0), 2)
                    # ---------------------------------- DeepSORT tacker work starts here ------------------------------------------------------------
                    features = self.encoder(frame, bboxes) # encode detections and feed to tracker. [No of BB / detections per frame, embed_size]
                    detections = [Detection(bbox, score, class_name, feature) for bbox, score, class_name, feature in zip(bboxes, scores, names, features)] # [No of BB per frame] deep_sort.detection.Detection object
                    cmap = plt.get_cmap('tab20b') #initialize color map
                    colors = [cmap(i)[:3] for i in np.linspace(0, 1, 20)]
                    boxs = np.array([d.tlwh for d in detections])  # run non-maxima supression below
                    scores = np.array([d.confidence for d in detections])
                    classes = np.array([d.class_name for d in detections])
                    indices = preprocessing.non_max_suppression(boxs, classes, self.nms_max_overlap, scores)
                    detections = [detections[i] for i in indices]       
                    self.tracker.predict()  # Call the tracker
                    self.tracker.update(detections) #  updtate using Kalman Gain
                    for track in self.tracker.tracks:  # update new findings AKA tracks
                        if not track.is_confirmed() or track.time_since_update > 1:
                            continue 
                        bbox = track.to_tlbr()
                        class_name = track.get_class()
                        color = colors[int(track.track_id) % len(colors)]  # draw bbox on screen
                        color = [i * 255 for i in color]
                        cv2.rectangle(frame, (int(bbox[0]), int(bbox[1])), (int(bbox[2]), int(bbox[3])), color, 2)
                        cv2.rectangle(frame, (int(bbox[0]), int(bbox[1]-30)), (int(bbox[0])+(len(class_name)+len(str(track.track_id)))*17, int(bbox[1])), color, -1)
                        cv2.putText(frame, class_name + " : " + str(track.track_id),(int(bbox[0]), int(bbox[1]-11)),0, 0.6, (255,255,255),1, lineType=cv2.LINE_AA)    

                        if verbose == 2:
                            print("Tracker ID: {}, Class: {},  BBox Coords (xmin, ymin, xmax, ymax): {}".format(str(track.track_id), class_name, (int(bbox[0]), int(bbox[1]), int(bbox[2]), int(bbox[3]))))

**Comment by prsnkmr** [comment]
when there is not detections in the frame,it will pass the input frame as output of the detections.detect function.

To avoid the error change the lines 105,109 in detection_helpers.py as shown in the image.

![error resolver](https://user-images.githubusercontent.com/110216641/181722140-c6becb11-d118-4071-9f24-9076b0610002.png)

you have to make some changes in bridge_wrappers.py

Add the line shown below after 98th line in bridge_wrappers.py

if yolo_dets is not None:

you need to indent the lines from 100 to 142 in the above metioned if loop .it works for me

**Comment by deshwalmahesh** [comment]
Thanks @prsnkmr  Yes, exactly. We just need to handle the things where there are no detection.  It's just Empty `Pytorch` Tensor trying to be converted to `numpy` array. I'll just return *original image* if there's no detection.

**Comment by deshwalmahesh** [comment]
Hi, 
@DARK-art108  @jgomeher83  @sivaji123256  @prsnkmr  Can any of you please take a pull of repo and let me know if the error has been handled for your use case? It works fine with me without any problem right now.
