### ISSUE TITLE
Apply in Webcam 

### ISSUE THREAD

**Issue by YLL0209** [deshwalmahesh/yolov7-deepsort-tracking#11]
Helooo, Is it possible that we can change any part so that can use this repository in webcam or any other camera?
Have a nice day!

**Comment by deshwalmahesh** [comment]
Hi @YLL0209  thanks for opening up the issue request. Di you have a chance to [look at the documentation for the function: `track_video`](https://github.com/deshwalmahesh/yolov7-deepsort-tracking/blob/master/bridge_wrapper.py#:~:text=def%20track_video(,0%20for%20webcam)
