### ISSUE TITLE
Colab crashes whenever I run the show mp4 video code in Colab 

### ISSUE THREAD

**Issue by ReemHassab** [deshwalmahesh/yolov7-deepsort-tracking#18]
from IPython.display import HTML
from base64 import b64encode

mp4 = open('trim.mp4','rb').read()
data_url = "data:video/mp4;base64," + b64encode(mp4).decode()
HTML("""<video width=400 controls><source src="%s" type="video/mp4"></video>""" % data_url)

whenever I run this code on Colab it automatically disconnects the runtime 
can someone help me with this?

**Comment by deshwalmahesh** [comment]
Yes, it is supposed to crash given the size in MBs, size in pixels. You can resize the video, convert a new format of the video, increase RAM for your Colab env etc. Or you can save and download it. It is Colab error, not the repo code. I'm assigning it as
