### ISSUE TITLE
Can I change the confidence value?

### ISSUE THREAD

**Issue by BoscoShin** [deshwalmahesh/yolov7-deepsort-tracking#23]
I tracked my source(detection person), but there was a misdetection part, so I'm going to increase the confidence to track it.

so can i change confidence(objectness threshold)?

**Comment by deshwalmahesh** [comment]
Hi, did you get a chance to look into the `Docstring` and functions?  Three out of Five paramns in [`Detector` class](https://github.com/deshwalmahesh/yolov7-deepsort-tracking/blob/master/detection_helpers.py) are for changing different thresholds. 

1. [Please visit this link](https://github.com/deshwalmahesh/yolov7-deepsort-tracking/blob/master/detection_helpers.py#:~:text=class%20Detector%3A,Class%2DAgnostic%20NMS) for Detector threshold - Confs
2. [Visit this link](https://github.com/deshwalmahesh/yolov7-deepsort-tracking/blob/master/bridge_wrapper.py#:~:text=max_cosine_distance%3A%20Cosine%20Distance,for%20the%20tracker) for Tracking Threshold / Confs
