### ISSUE TITLE
How to get the Tracking ID 

### ISSUE THREAD

**Issue by VM8198** [deshwalmahesh/yolov7-deepsort-tracking#26]
Everything is running fine but I'm just curious how to get the tracking id in the processed video. Because the example video you have posted showing the tracking id but not able to get it when I'm running the example

**Comment by deshwalmahesh** [comment]
Please see if [this similar problem's answer](https://github.com/deshwalmahesh/yolov7-deepsort-tracking/issues/7) helps. everything is in one file and you can print, modify etc etc
