### ISSUE TITLE
How to do custom yolov7 object tracking setup

### ISSUE THREAD

**Issue by KarthikArumugam3** [deshwalmahesh/yolov7-deepsort-tracking#4]
I want to do the same object tracking setup for my custom yolov7 project, I have 2 classes only, how to setup the whole project with my custom class names & weights file? Please guide me, with the complete steps for custom setup and the changes & the modifications needed to do in this repository setup for the same.

**Comment by deshwalmahesh** [comment]
Hey @KarthikArumugam3 , tracking needs two major things. 
1. Detection
2. `ReID` model to get similarity between the detected objects

What you can do is to first learn how `Yolov-7` is trained on custom dataset, which might not be very different from any of the `YOLO` versions starting from `v4`.  Once you have trained your object detection model, it means you have all the classes name and configurations set up corrected already.

Now the trickiest part is to train a model `DeepSORT: ReID` model which gets the similarity between objects. You can train a `Siamese model` trained on your objects and use it to pass the detected BBs.

In the simplest sense, you need to first learn how `DeepSORT` works. It can use **ANY** detection model as long as it is getting patches (BB) of images then checks the similarity between the same.

**Comment by deshwalmahesh** [comment]
@KarthikArumugam3  You can follow [This video on fine tuning custom dataset](https://learnopencv.com/fine-tuning-yolov7-on-custom-dataset/)

Then train a Siamese model for the `ReID` for `DeepSORT`.
