### ISSUE TITLE
Trim an existing video

### ISSUE THREAD

**Issue by hasanmemis21** [deshwalmahesh/yolov7-deepsort-tracking#5]
this part is missing, it doesn't work if you don't add it
"!pip install imageio-ffmpeg"

**Comment by deshwalmahesh** [comment]
Hey, thanks for pointing out :)

**Comment by hasanmemis21** [comment]
I thank you, you are the best repository on this subject and you wrote it perfectly

**Comment by deshwalmahesh** [comment]
Thank you very much @hasanmemis21 for your kind words
