### ISSUE TITLE
Docker for Yolov7 and Deepsort/Tracking

### ISSUE THREAD

**Issue by Kannan665** [deshwalmahesh/yolov7-deepsort-tracking#6]
@deshwlmahesh.....I am not posting this as any "issue".........I had spun a docker file for Yolov7 and Deepsort/Tracking a week or two before, basically using all the resources from your Github repository......And a group of developers also worked on it,  who were all present in a hackathon to develop SMART City solutions......The docker file did what it is supposed to do.....Virtualization and Isolation and touchwood, no issues.......During the next couple of days, I need to share it to my other terminals, and see how it works,.......I had used datamachines pre-built docker image for building the docker file......I will share it here, once I am able to replicate the same results that I had in my workstation on my other machines.........FYI, I am not a coder.....My domain is Operations/Manufacturing and I am learning AI/DL more for fun and see how I can bridge the gap between IT and OT in manufacturing organizations........

**Comment by deshwalmahesh** [comment]
Hey @Kannan665  Thank you very much that you found the things useful. I'll be happy to put up your `DockerFile` once you're done with your things. Please fell free to open up a merge request. I'm glad that being a non IT person, you've already learned so much. Keep on growing :)
